service: e-commerce-serverless-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false

functions:
  cart:
    events:
      - http:
          method: POST
          path: carts/process
    handler: ./src/api/handlers/CartHandler.handler
